version: "3.4"
services:

  nginx:
    image: cytomine/nginx:v1.3.1
    container_name: nginxTest
    hostname: nginxTest
    ports: [ "80:80" ]
    restart: unless-stopped
    volumes:
      - "./config/nginx/nginxCORS.conf:/usr/local/nginx/conf/nginx.conf"
    links:
      - "core:core"

  core:
    image: cytomine/core:pims-20220519145221-SNAPSHOT
    restart: unless-stopped
    ports: [ "8090:8080" ]
    volumes:
      - "./config/application.yml:/app/application.yml"
      - "./config/addHosts.sh:/tmp/addHosts.sh"
    links:
      - "postgresql:postgresql"
      - "mongodb:mongodb"
      - "rabbitmq:rabbitmq"

  postgresql:
    image: cytomine/postgis:v2.0.0
    restart: unless-stopped

  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=cytomine

  rabbitmq:
    image: cytomine/rabbitmq:v1.1.2
    ports: [ "5672:5672", "15672:15672" ]
    restart: unless-stopped
